# Generated by Django 2.2.6 on 2019-10-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=24)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todos.Character')),
            ],
        ),
    ]
